INSERT INTO Publisher (name)
VALUES ('HarperCollins'),
       ('Tor Books'),
       ('Penguin Random House'),
       ('Orbit Books'),
       ('Del Rey Books'),
       ('Gollancz'),
       ('Ace Books'),
       ('Bantam Books'),
       ('Ballantine Books'),
       ('Daw Books'),
       ('Simon & Schuster'),
       ('Hodder & Stoughton'),
       ('Voyager Books'),
       ('Little, Brown and Company'),
       ('Subterranean Press'),
       ('G.P. Putnam''s Sons'),
       ('Roc Books'),
       ('Baen Books'),
       ('Macmillan Publishers'),
       ('Random House');