INSERT INTO Author (name, surname)
VALUES ('J.R.R.', 'Tolkien'),
       ('George R.R.', 'Martin'),
       ('J.K.', 'Rowling'),
       ('Terry', 'Brooks'),
       ('Terry', 'Goodkind'),
       ('Robert', 'Jordan'),
       ('Brandon', 'Sanderson'),
       ('Patrick', 'Rothfuss'),
       ('Neil', 'Gaiman'),
       ('Terry', 'Pratchett'),
       ('C.S.', 'Lewis'),
       ('Philip', 'Pullman'),
       ('Ursula K.', 'Le Guin'),
       ('Robin', 'Hobb'),
       ('Raymond E.', 'Feist'),
       ('Brian', 'Jacques'),
       ('David', 'Eddings'),
       ('Mercedes', 'Lackey'),
       ('Margaret', 'Weis'),
       ('Tracy', 'Hickman');