INSERT INTO Book (name, publisher_id)
VALUES ('The Hobbit', 1),
       ('The Lord of the Rings', 1),
       ('A Game of Thrones', 2),
       ('A Clash of Kings', 2),
       ('Harry Potter and the Philosopher''s Stone', 3),
       ('Harry Potter and the Chamber of Secrets', 3),
       ('Mistborn: The Final Empire', 4),
       ('The Name of the Wind', 5),
       ('American Gods', 6),
       ('Good Omens', 6),
       ('The Lion, the Witch and the Wardrobe', 7),
       ('Northern Lights', 8),
       ('A Wizard of Earthsea', 9),
       ('Assassin''s Apprentice', 10),
       ('Magician', 11),
       ('Redwall', 12),
       ('Pawn of Prophecy', 13),
       ('Arrows of the Queen', 14),
       ('Dragons of Autumn Twilight', 15),
       ('The Silmarillion', 1),
       ('A Storm of Swords', 2),
       ('Harry Potter and the Prisoner of Azkaban', 3),
       ('Words of Radiance', 4),
       ('The Wise Man''s Fear', 5);