spring:
  application:
    name: tpo03
  profiles:
    active: lowercase
  banner:
    location: logo-app
    charset : utf-8
  datasource:
    url: jdbc:h2:file:./db/mydatabase
    username: s27591
    password: password
  h2:
    console:
      path: /my-h2-console
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
pl:
  edu:
    pja:
      tpo02:
        filename: "src/main/resources/dictionary.csv"