INSERT INTO blog (name, manager_id)
VALUES
    ('SuperFunnyBlog1', 1),
    ('SuperFunnyBlog2', 2),
    ('SuperFunnyBlog3', 3),
    ('SuperFunnyBlog4', 4),
    ('SuperFunnyBlog5', 5),
    ('SuperFunnyBlog6', 6),
    ('SuperFunnyBlog7', 7),
    ('SuperFunnyBlog8', 8),
    ('SuperFunnyBlog9', 9),
    ('SuperFunnyBlog10', 10),
    ('SuperFunnyBlog11', 11),
    ('SuperFunnyBlog12', 12),
    ('SuperFunnyBlog13', 13),
    ('SuperFunnyBlog14', 14),
    ('SuperFunnyBlog15', 15),
    ('SuperFunnyBlog16', 16),
    ('SuperFunnyBlog17', 17),
    ('SuperFunnyBlog18', 18),
    ('SuperFunnyBlog19', 19),
    ('SuperFunnyBlog20', 20);
