INSERT INTO Article (title, author_id, blog_id)
VALUES ('MegaFascinatingArticle1', 1, 20),
       ('MegaFascinatingArticle2', 1, 17),
       ('MegaFascinatingArticle3', 2, 2),
       ('MegaFascinatingArticle4', 3, 2),
       ('MegaFascinatingArticle5', 4, 5),
       ('MegaFascinatingArticle6', 4, 6),
       ('MegaFascinatingArticle7', 5, 13),
       ('MegaFascinatingArticle8', 6, 19),
       ('MegaFascinatingArticle9', 7, 9),
       ('MegaFascinatingArticle10', 7, 10),
       ('MegaFascinatingArticle11', 8, 16),
       ('MegaFascinatingArticle12', 9, 12),
       ('MegaFascinatingArticle13', 30, 13),
       ('MegaFascinatingArticle14', 25, 1),
       ('MegaFascinatingArticle15', 24, 7),
       ('MegaFascinatingArticle16', 20, 7),
       ('MegaFascinatingArticle17', 23, 17),
       ('MegaFascinatingArticle18', 4, 16),
       ('MegaFascinatingArticle19', 10, 20),
       ('MegaFascinatingArticle20', 27, 7);
