spring:
  application:
    name: tpo04Books
  h2:
    console:
      path: /my-console
  datasource:
    url: jdbc:h2:mem:books
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:sql-data/*.sql